num_clients: 10
fraction_fit: 0.5
num_rounds: 50
local_epochs_head: 3
local_epochs_base: 2
batch_size: 32
learning_rate: 0.01
momentum: 0.9
dirichlet_alpha: 0.5  # Change this to 0.01, 0.1, 1.0, or 'IID' for your sweep
dataset: "FMNIST"